// Generated by https://quicktype.io

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HoggitWeaponPointsKneeboardExporter
{
    public class Weapons
    {
        [JsonPropertyName("points")]
        public long Points { get; set; }

        [JsonPropertyName("category")]
        public string Category { get; set; }
        public static Dictionary<string, Weapons> FromJson(string json) 
            => JsonSerializer.Deserialize<Dictionary<string, Weapons>>(json);
    }
}
